# The URL the site will be built for
base_url = "https://blog.ymgyt.io"

title = "Happy developing"

description = "楽しい開発ライフ"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
# https://www.getzola.org/documentation/content/search/
build_search_index = false

output_dir = "public"

hard_link_static = false

# search index for language ja which is not supported
default_language = "ja"

# Feed configuration
generate_feeds = true
feed_filenames = ["atom.xml"]
author = "ymgyt"

taxonomies = [{ name = "tags", feed = true, render = true }]

[languages.en]
title = "Happy developing"
description = "Happy developing"
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags", feed = true, render = true }]

[translations]
nav_entries = "Entries"
nav_tags = "Tags"
nav_about = "About"
language_switch_label = "Translations"
language_name_ja = "日本語"
language_name_en = "English"
tags_title = "Tags"
tag_entries_title = "entries"

[languages.en.translations]
nav_entries = "Entries"
nav_tags = "Tags"
nav_about = "About"
language_switch_label = "Translations"
language_name_ja = "Japanese"
language_name_en = "English"
tags_title = "Tags"
tag_entries_title = "entries"


[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = false

[markdown.highlighting]
theme = "nord"
# style = "class"
style = "inline"

# Various slugification strategies
[slugify]
# Respect entry "_" for compability
paths = "safe"
taxonomies = "on"
anchors = "on"

[link_checker]

# Treat internal link problems as either "error" or "warn", default is "error"
internal_level = "error"

# Treat external link problems as either "error" or "warn", default is "error"
external_level = "error"

# Skip link checking for external URLs that start with these prefixes
skip_prefixes = []

skip_anchor_prefixes = [
  # Github line link does not work with link checker
  # ex. mod.rs#L237-L241
  "https://github.com",
]

[extra]
# Put all your custom variables here

[extra.author]
name = "ymgyt"
github = "ymgyt"
twitter = "YAmaguchixt "
