[package]
name = "blogir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = []
parser = ["nom"]

[dependencies]
nom = { version = "7.1.1", optional = true }
thiserror = "1.0.31"
